# Development environment configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simior-blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}

  data:
    redis:
      host: localhost # Redis服务器地址
      port: 6379 # Redis服务器连接端口
      database: 0 # Redis数据库索引（默认为0）
      password:  # Redis服务器连接密码（默认为空）

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出 SQL 日志到控制台

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
    org.simior: debug

blog:
  upload:
    mode: minio
    # MinIO配置
    minio:
      endpoint: http://127.0.0.1:9000
      access-key: ${MINIO_ACCESS_KEY:admin}
      secret-key: ${MINIO_SECRET_KEY:password123456}
      bucket-name: simior-blog